name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Install tera-cli from git
      uses: baptiste0928/cargo-install@v2
      with:
        crate: teracli
        git: https://github.com/chevdor/tera-cli
        tag: v0.2.4

    - name: Run build script
      run: sh build.sh

    # Deploy to local repo
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        publish_branch: gh-pages
